export const types = {
    setEstados: '[status] Show Form',
    setModalVisible: '[status] Validate Form',
    setNombreEstado: '[status] Project Now',
    setEstadoEditado: '[status] Delete Project',

    setUser: '[User] Agregar usuario al contexto',
    setUsers: '[User] Agregar usuarios al contexto',
    setIsLoggedIn: '[status] Show Form',
    // showForm: '[project] Show Form',
    // getProjects: '[project] Get Projects',
    // addProject: '[project] Add Projects',
    // validateForm: '[project] Validate Form',
    // projectNow: '[project] Project Now',
    // deleteProject: '[project] Delete Project',

    // getTasks: '[task] Get Tasks',
    // addTask: '[task] Add Task',
    // validateTask: '[task] Validate Task',
    // deleteTask: '[task] Delete Task',
    // stateTask: '[task] Change State Task',
    // taskNow: '[task] Edit Task',
    // updateTask: '[task] Update Task',
    // clearTask: '[task] Clear Task',
} 